Repository betaflight/betaflight.com, pull requests merged in 2024-04, with the labels that each got.

#406 Fetch sponsor banner from BF server
  docs/development/API/Dshot.mdx
  docs/development/manufacturer/connector-standard.md
  docs/relations/sponsors.mdx
  package-lock.json
  package.json
  src/components/Home/index.tsx
  src/components/Sponsors/Sponsors.tsx
  src/css/custom.css
  src/theme/Footer/Layout/index.js
Labels: javascript

#410 Cycle Sponsor Logos and Optimize Styling
  src/components/Sponsors/Sponsors.tsx
  src/css/custom.css
Labels: typescript

#414 More space between sponsor logos
  src/components/Sponsors/Sponsors.tsx
  src/css/custom.css
Labels: enhancement

#416 small Angle Mode notes change
  docs/wiki/release/Betaflight-4-5-Release-Notes.md
Labels: Ready to Merge
