Repository betaflight/betaflight.com, pull requests merged in 2024-01, with the labels that each got.

#318 Update Katex
  docs/development/mdx-reference.md
  package-lock.json
  package.json
Labels: dependencies

#313 Update cloud build API documentation
  docs/development/api/Cloud-Build-API.md
Labels: enhancement, bugfix

#315 Make Logos Adapt to Color Theme
  docs/development/manufacturer/connector-standard.md
  docs/development/manufacturer/manufacturer-design-guidelines.mdx
  docs/relations/partner.mdx
  docs/relations/sponsors.mdx
  src/components/Home/index.tsx
  src/css/custom.css
  src/pages/sponsors.md
  src/pages/sponsors.mdx
  static/img/betaflight/sponsors/Axisflying_dark.svg
  static/img/betaflight/sponsors/axisflying_dark.svg
  static/img/betaflight/sponsors/axisflying_light.svg
  static/img/betaflight/sponsors/hqprop.svg
  static/img/betaflight/sponsors/radiomaster-logo.jpg
Labels: bugfix, javascript

#327 Update mag i2c and IST8310 notes
  docs/wiki/guides/current/Magnetometer.md
Labels: Ready to Merge

#333 Make Dogcom logo adapt to color theme
  docs/relations/sponsors.mdx
  src/components/Home/index.tsx
  static/img/betaflight/sponsors/dogcom.svg
  static/img/betaflight/sponsors/dogcom_dark.svg
  static/img/betaflight/sponsors/dogcom_light.svg
Labels: enhancement
